name: flutter_qr_scanner
description: "Safe Qr Scanner for everyone!"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  flutter_svg: ^2.0.7  # added 
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  url_launcher: ^6.0.12
  crypto: ^3.0.3
  public_suffix: ^3.0.0
  http: ^1.6.0

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename: ^3.1.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/icons/